### ISSUE TITLE
update profile configuration file

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#751]
Current `cucumber.js` file
```js
var common = [
  '--compiler js:babel-register',
  '--format progress',
  '--format rerun:@rerun.txt',
  '--format usage:usage.txt'
].join(' ')

module.exports = {
  'default': common,
  'node-4': common + ' --tags "not @node-6"',
};
```
Suggested update new `cucumber.yml` file (using references)
```yml
_common: &COMMON
  compiler: js:babel-register
  format:
    - progress
    - rerun:@rerun.txt
    - usage:usage.txt

default:
  <<: *COMMON

node-4:
  <<: *COMMON
  tags: not @node-6
```

@jbpros thoughts? We originally went with `.js` in order to avoid the clash with ruby's `cucumber.yml` but I don't see think thats as an issue. Aside from this project when I first joined, I've never seen a project that used both `cucumber-ruby` and `cucumber-js`. Nor can I think of a valid reason to do so.

@mattwynne you as well as you may be able to get rid of the erb support. 

Mainly would like to allow users to not have put actual CLI options in here. The options mirror the long form of the CLI options but without the need of actually specifying them with all the `--`. Implementation wise you can still convert these to cli options pretty easily (on the javascript side the there is a javascript library for doing that: [dargs](https://github.com/sindresorhus/dargs).
